[project]
name = "test-case"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=25.1.0",
    "asyncio>=4.0.0",
    "ruff>=0.15.0",
    "tabulate>=0.9.0",
]
